### ISSUE TITLE
EOF SSL Error

### ISSUE THREAD

**Issue by danowitz** [IndigoDomotics/indigo-ecobee-plugin#14]
I am now getting the following error.

```
Traceback (most recent call last):
  File "plugin.py", line 168, in runConcurrentThread
  File "/Library/Application Support/Perceptive Automation/Indigo 7.2/Plugins/Ecobee.indigoPlugin/Contents/Server Plugin/pyecobee/__init__.py", line 123, in refresh_tokens
  File "/Library/Application Support/Perceptive Automation/Indigo 7.2/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 111, in post
  File "/Library/Application Support/Perceptive Automation/Indigo 7.2/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/api.py", line 57, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7.2/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 477, in request
  File "/Library/Application Support/Perceptive Automation/Indigo 7.2/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/sessions.py", line 587, in send
  File "/Library/Application Support/Perceptive Automation/Indigo 7.2/IndigoPluginHost.app/Contents/Resources/PlugIns/requests/adapters.py", line 491, in send
SSLError: EOF occurred in violation of protocol (_ssl.c:590)
```

I am running Indigo 7.2 and plugin version 1.2.3.

Thoughts?

Thanks
Joel

**Comment by FlyingDiver** [comment]
You're still on Sierra or earlier macOS?

**Comment by danowitz** [comment]
Hey, yes I have kept the Mac Mini that is running indigo back from OS updates (its El Cap) because of everything I have read on the Indigo site that talks about trouble people have with the new versions of the OS. Should I update the machine?  Should I go with Mojave?

Thanks Joel

**Comment by FlyingDiver** [comment]
The only fix is to go to High Sierra or Mojave.  I'm running Mojave on my development MacBook Pro with no issues, but I don't have any USB devices attached to it.  My production machine is 2010 Mac Pro and no issues with High Sierra on it.
